### ISSUE TITLE
Error Contacting Api : staus{statusCode= PLACES_API_ACCESS_NOT_CONFIGURED,RESOLUTION=null}

### ISSUE THREAD

**Issue by MinaSamir11** [mitchtabian/Google-Maps-Google-Places#8]
after typing any location this error appear ..
i tried to disable and enable places API more than once still same error .. 
help please :(

**Comment by A-M-A96** [comment]
SAME HERE

**Comment by MinaSamir11** [comment]
AMaMinou  i found the problem and solve it by searching to new methods of place api 
because all of methods you are using is deprecated :)

**Comment by A-M-A96** [comment]
could u help me please ?? @MinaSamir11

**Comment by MinaSamir11** [comment]
https://developers.google.com/places/android-sdk/client-migration 

Check this link and follow steps 
* hint : Start a new project
